// src/components/AboutMe/index.tsx
import React from 'react';
import clsx from 'clsx';
import styles from './styles.module.scss';
import Link from '@docusaurus/Link';

type FeatureItem = {
  title: string;
  date: string;
  Svg?: React.ComponentType<React.ComponentProps<'svg'>>;
  description: JSX.Element;
};

const FeatureList: FeatureItem[] = [
  {
    title: 'MLOps Developer',
    date: 'September 2021 - Current',
    // Svg: require('@site/static/img/about-me/macintosh.svg').default,
    description: (
      <>
        ML system integration, Orchestrate the steps in ML, Automation&nbsp;
        <br />
        ∙ Full stack MLOps developer responsible for end-to-end data ingestion, training, deployment lifecycle.
        <br />
        ∙ Prototype development and commercialization
        <br />
        ∙ Drive best practice implementation for across company
        <br /><br />
        <p style={{fontWeight:"bold"}}>Skills:&nbsp;
          <Link href="https://jwher.github.io/categories/server/fastapi" className={styles.btn__warning}>FastAPI</Link>
          <Link href="https://jwher.github.io/categories/mlops/mlflow" className={styles.btn__warning}>MLflow</Link>
          <Link href="https://jwher.github.io/categories/pytorch" className={styles.btn__warning}>Pytorch</Link>
          <Link href="https://jwher.github.io/categories/web/angular" className={styles.btn__warning}>Angular</Link>
          <Link href="https://jwher.github.io/categories/ml/deepstream" className={styles.btn__warning}>Deepstream</Link>
        </p>
      </>
    ),
  },
  {
    title: 'MLOps Engineer',
    date: 'March 2021 - September 2021',
    Svg: require('@site/static/img/about-me/wrench.svg').default,
    description: (
      <>
        MLOps product survey and implementation for labeling toolset&nbsp;
        <br />
        ∙ Adopting kubernetes for scalable infrastructure
        <br />
        ∙ Automate training pipeline for pseudo-labeling feature
        <br />
        ∙ Deploy model using serverless framework
        <br /><br />
        <p style={{fontWeight:"bold"}}>Skills:&nbsp;
          <Link href="/categories/kubernetes" className={styles.btn__success}>Kubernetes</Link>
          <Link href="/categories/kubernetes/kubeflow" className={styles.btn__success}>Kubeflow</Link>
          <Link href="/categories/ml/openvino" className={styles.btn__warning}>OpenVINO</Link>
          <Link href="/categories/ml/nuclio" className={styles.btn__success}>Nuclio</Link>
          <Link href="/categories/web/angular" className={styles.btn__warning}>React</Link>
        </p>
      </>
    ),
  },
  {
    title: 'Java Backend Developer',
    date: 'January 2020 - February 2020',
    Svg: require('@site/static/img/undraw_docusaurus_tree.svg').default,
    description: (
      <>
        Winter internship
        <br />
        ∙ Survey top blockchain trends
        <br />
        ∙ Develope logic to find a specific transaction on distributed ledger
        <br /><br />
        <p style={{fontWeight:"bold"}}>Skills:&nbsp;
          <Link href="/categories/java/spring" className={styles.btn__success}>Spring</Link>
          <Link href="/categories/web/node" className={styles.btn__success}>Node.js</Link>
        </p>
      </>
    ),
  },
  {
    title: 'Education',
    date: 'March 2015 - February 2021',
    Svg: require('@site/static/img/about-me/graduation-cap.svg').default,
    description: (
      <>
        Dongguk University. seoul, Korea
        <br />
        ∙ Received a bachelor's degree in Computer Science
        <br />
        ∙ Followed my passion in cloud computing classes
        <br />
        ∙ Worked as an assistant for programming language and parallel computing
        <br />
        ∙ Military service from Feb. 2016 until Nov. 2017
        <br /><br />
        <p style={{fontWeight:"bold"}}>Skills:&nbsp;
          <Link href="/categories/cs/algorithm" className={styles.btn__warning}>Algorithm</Link>
          <Link href="/categories/cs/design-pattern" className={styles.btn__warning}>Design Pattern</Link>
          <Link href="/categories/cs/operating-system" className={styles.btn__warning}>OS</Link>
          <Link href="/categories/cs/parallel-programming" className={styles.btn__warning}>Parallel Programming</Link>
        </p>
      </>
    ),
  },
  // {
  //   title: 'Powered by React',
  //   date: '',
  //   Svg: require('@site/static/img/undraw_docusaurus_react.svg').default,
  //   description: (
  //     <>
  //       Extend or customize your website layout by reusing React. Docusaurus can
  //       be extended while reusing the same header and footer.
  //     </>
  //   ),
  // },
];

function Feature({ title, date, Svg, description }: FeatureItem) {
  return (
    <div className={styles.timeline}>
      <div className={styles.timeline__icon}>
        <span className={styles.year}>{date}</span>
      </div>
      <div className={styles.timeline__content}>
        {Svg ?
          <div className="text--center">
            <Svg className={styles.featureSvg} role="img" />
          </div> : <></>
        }
        <h3 className={styles.title}>{title}</h3>
        <p className={styles.description}>
          {description}
        </p>
      </div>
    </div>
  );
}

export default function AboutMe(): JSX.Element {
  return (
    <section className={styles.features}>
      <div className="container">
        <br />
        <h1 className="card-title">About Me</h1>
        <br />
        <div className={styles.card__body}>
          <h3>My name is Jeongwon Her. I have the following qualities</h3>
          ∙ Back-end programming languages: Python, Java, C#
          <br/>
          ∙ Back-End Framework: .NET, Spring Framework, FastAPI
          <br/>
          ∙ Front-End Framework: Angular, React
          <br/>
          ∙ Databases: MySQL, PostgreSQL, MongoDB
          <br/>
          ∙ Version control: Git
          <br/>
          ∙ DevOps, Docker, Kubernetes
          <br/><br/>
          ∙ Bachelor's degree in Computer Science
          <br />
          ∙ Passionate about automating repetitive tasks especially machine learning
          <br />
          ∙ Currently working as mlops developer
          <br /><br />
          ✉️ hacel@naver.com
          <br />
        </div>
        <br />
      </div>
      <hr></hr>
      <div className="container">
        <h1 className="card-title">Timeline</h1>
        <br />
        <div className="row">
          <div className="col-md-12">
            <div className={styles.main__timeline}>
              {FeatureList.map((props, idx) => (
                <Feature key={idx} {...props} />
              ))}
            </div>
          </div>
        </div>
      </div>
      <div className="container" style={{padding: 0, maxWidth: "none"}}>
        <div className={styles.rainbow}>
          <div>Come unto me, all ye that labour and are heavy laden, and I will give you rest</div>
        </div>
      </div>
    </section>
  );
}

// src/app/components/about-me/about-me.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about-me',
  templateUrl: './about-me.component.html',
  styleUrls: ['./about-me.component.scss']
})
export class AboutMeComponent implements OnInit {

  data: {media_url:string, caption:string}[]=[];
  constructor() {
  }
  
  ngOnInit(): void {
    (
      async () => {
        const response = await fetch('/api/me/media?fields=id,caption&access_token=IGQVJVNW5TbldjdWo5NkhCeDRvOUFLUU55a2xsbUtJSXllaUFZAYmozUUFoNnNERUZACOXpENG9kUFMwcGlHd3B4YnpheEV3ODRrcFA0QVpoa1ZApOVpleGlNVUlZAU1ZAMQ21ZAbGRvdy1nOVdMQW9ZAQWhDTAZDZD');
        let mediaList: {data:Array<{id:string, caption:string}>} = await response.json();
        console.log(mediaList);
        for(const media of mediaList.data){
          // console.log("media:"+media);
          const response = await fetch('/api/'+media.id+'?fields=media_type,media_url&access_token=IGQVJVNW5TbldjdWo5NkhCeDRvOUFLUU55a2xsbUtJSXllaUFZAYmozUUFoNnNERUZACOXpENG9kUFMwcGlHd3B4YnpheEV3ODRrcFA0QVpoa1ZApOVpleGlNVUlZAU1ZAMQ21ZAbGRvdy1nOVdMQW9ZAQWhDTAZDZD');
          let result:{media_type:string, media_url:string} = await response.json();
          console.log(result);
          if(result.media_type=='IMAGE'){
            this.data.push({media_url:result.media_url, caption:media.caption});
          }
        }
        console.log(this.data);
      }
    )();
      
  }
}

<div class="section">
    <div class="container tim-container">
        <div class="tim-title">
            <h2 class="title">About Me</h2>
            <br/>
        </div>
        <div class="typography-line">
            <h3>My name is JeongWon Her. I have the following qualities:</h3>
            <br />
        </div>
        <div class="typography-line">
            <p>
                Languages: Python, Java, TypeScript
                <br />
                Technologies: Pytorch, ONNX, Deepstream, Alembic, Angular
                <br />
                DevOps: CI/CD(github workflow), Docker(Harbor), Kubernetes(On premise)
                <br />
                Culture: Linux, Open Source, MSA
                <br />
                Methodology: Agile
            </p>
        </div>
    </div>
</div>

<app-recent-posts></app-recent-posts>

<div class="section">
    <div class="container tim-container">
        <div class="tim-title">
            <h2 class="title">Experience</h2>
            <br/>
        </div>
        <div class="typography-line">
            <p style="font-style: italic;">
                MLOps engineer<br />
                September 2021 - Current<br />  
                Seoul, Korea<br />
            </p>
            <p>
                ML system integration, Orchestrate the steps in ML, Automation
                <a href="#" class="btn btn-outline-warning">MLOps</a>
                <br />
                1. Project setup
                <a href="#" class="btn btn-outline-warning">SDLC</a>
                <br />
                2. Data & ML pipeline
                <a href="https://jwher.github.io/categories#minio" class="btn btn-outline-warning">minIO</a>&nbsp;
                <a href="https://jwher.github.io/categories#airflow" class="btn btn-outline-warning">Airflow</a>
                <br />
                3. Training
                <a href="https://jwher.github.io/categories#mlflow" class="btn btn-outline-warning">MLFlow</a>
                <br />
                4. Serving
                <a href="https://jwher.github.io/categories#bento" class="btn btn-outline-warning">Bento</a>
                <br />
                Technologies: FastAPI, Pytorch, Docker
                <br />
                Culture: Linux, Open Source, Github
            </p>
            <br />
            <p style="font-style: italic;">
                MLOps engineer<br />
                March 2021 - September 2021<br />  
                Certiware<br />
                Seoul, Korea<br />
            </p>
            <p>
                MLOps product survey and implementation
                <br />
                1. Managing Kubernetes
                <a href="https://jwher.github.io/categories#kubernetes" class="btn btn-outline-success">Kubernetes</a>
                <br />
                2. Model pipeline
                <a href="https://jwher.github.io/categories#kubeflow" class="btn btn-outline-success">Kubeflow</a>
                <br />
                3. Modeling & Training
                <a href="https://jwher.github.io/categories#ml" class="btn btn-outline-success">ML</a>
                <br />
                4. Serving
                <a href="https://jwher.github.io/categories#nuclio" class="btn btn-outline-success">Nuclio</a>
                <br />
                Technologies: Kubernetes, Kubeflow, Pytorch, Docker, TypeScript(React)
                <br />
                Culture: Linux, Open Source, Gitlab
            </p>
            <br />
            <p style="font-style: italic;">
                Java Backend Developer<br />
                2 months (January 2020 - February 2020)<br />
                Hivvlab<br />
                Seoul, Korea<br />
            </p>
            <p>
                Winter internship  
                <br />
                1. Researching top blockchain trends
                <br />
                2. Find a specific transaction in distributed ledger
                <br />
                3. Process transaction data and insertion

                Technologies: Java, Node.js  
                <br />
                Culture: Spring-svn
            </p>
        </div>
    </div>
</div>
<div class="section">
    <div class="container tim-container">
        <div class="tim-title">
            <h2 class="title">Education</h2>
            <br/>
        </div>
        <div class="typography-line">
            <p style="font-style: italic;">
                Dongguk University<br />
                4 years (March 2015 - February 2021)<br />
                Seoul, Korea<br />
            </p>
            <p>
                I've learned Computer Science and Engineering  
                <br />
                <a href="https://jwher.github.io/categories#cs" class="btn btn-outline-warning">Data Structure</a>&nbsp;
                <a href="https://jwher.github.io/categories#cs" class="btn btn-outline-warning">Algorithm</a>&nbsp;
                <a href="https://jwher.github.io/categories#cs" class="btn btn-outline-warning">Disign Pattern</a>&nbsp;
                <a href="https://jwher.github.io/categories#cs" class="btn btn-outline-warning">OS</a>&nbsp;
                <a href="https://jwher.github.io/categories#cs" class="btn btn-outline-warning">Parallel Programming</a>&nbsp;
                <br />
                Military service from Feb. 2016 until Nov. 2017
            </p>
        </div>
    </div>
    <br/>
</div>
<div class="section" id="carousel">
    <div class="container tim-container">
        <div class="tim-title">
            <h3 class="title">My story</h3>
        </div>
        <div class="card page-carousel">
            <ngb-carousel>
                <ng-template ngbSlide *ngFor="let d of this.data">
                    <img src="{{d.media_url}}" alt="{{d.caption}}">
                    <div class="carousel-caption">
                        <p>{{d.caption}}</p>
                    </div>
                </ng-template>
            </ngb-carousel>
        </div>
    </div>
</div>

<div class="section">
    <div class="rainbow-image">
        <div class="rainbow"></div>
        <div class="rainbow"></div>
        <div class="rainbow"></div>
        <div class="rainbow"></div>
        <div class="rainbow"></div>
        <div class="rainbow"></div>
    </div>
</div>

<div class="section">
    <div class="container tim-container">
        <blockquote class="blockquote">
            <br />
            <p>What else do you need?</p>
            hacell2@gamil.com
            <p> </p>
            <br />
            <app-social-links>
            </app-social-links>
            <br />
        </blockquote>
        <div class="support">
            <a href="https://www.buymeacoffee.com/jwher">
                <img src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=jwher&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000&coffee_colour=ffffff" />
            </a>
        </div>
    </div>
</div>
